### ISSUE TITLE
Cannot Open Control Panel

### ISSUE THREAD

**Issue by MSC19950601** [QIICR/LongitudinalPETCT#14]
I installed the newest bulid version 4.8.11, install from Extensional Module Zoo. But I cannot find the main panel of this Module, only help, and acknowledgement.

**Comment by jcfr** [comment]
Thanks for the report, I confirm the issue.

Error is the following:

```
Loading Slicer RC file [/home/jcfr/.slicerrc.py]
Traceback (most recent call last):
  File "/home/jcfr/.config/NA-MIC/Extensions-27501/LongitudinalPETCT/lib/Slicer-4.10/qt-loadable-modules/Python/qSlicerLongitudinalPETCTModuleWidget.py", line 432, in setup
    self.__createEditorWidget()
  File "/home/jcfr/.config/NA-MIC/Extensions-27501/LongitudinalPETCT/lib/Slicer-4.10/qt-loadable-modules/Python/qSlicerLongitudinalPETCTModuleWidget.py", line 99, in __createEditorWidget
    self.editorWidget = EditorWidget(editorWidgetParent, False)
NameError: global name 'EditorWidget' is not defined
```

**Comment by jcfr** [comment]
@MSC19950601 Waiting a new extension is uploaded and available for download, you could locally fix the error.

To do so, following these steps:

1. Open the error log (red icon on the bottom right)

2. Identify the path of the script where the error happen

3. Update the script like it was done in https://github.com/jcfr/LongitudinalPETCT/commit/7384ab12ac59e30d5e7bc8552e9a1b00c3d44963

4. Restart Slicer

**Comment by MSC19950601** [comment]
I have fixed the bug following your solution, 3Q 👍

**Comment by MSC19950601** [comment]
@jcfr Two more question. 
**The PET/CT FUSION MODULE in slicer 3.6 was moved to which module?
How to draw ROI/VOI without filling them?**
Thank you for your patience!

**Comment by pieper** [comment]
Not all features of 3.6 moved one-to-one into 4.x . You can have a look at the PET-related extensions for 4.10 and see if they meet your needs.

You can paint outlines in the Segment Editor, or you can create filled segments and [then hollow them out](https://discourse.slicer.org/t/new-segment-editor-effect-for-creating-hollow-objects/2464/2).
